import json
import boto3
import os

def lambda_handler(event, context):
    try:
        # ========================================================
        # 1) Parse input from API Gateway
        # ========================================================
        # Check if this is a warmer ping from EventBridge
        if event.get("source") == "aws.events" and event.get("detail-type") == "Scheduled Event":
            print("Received ping from EventBridge... Warming Lambda!")
            return {"statusCode": 200, "body": "Warm"}

        body_str = event.get("body", "{}")
        body = json.loads(body_str)
        
        job_description = body.get("job_description")
        resume_text = body.get("resume_text")
        
        if not job_description or not resume_text:
            return {
                "statusCode": 400,
                "headers": {
                    "Access-Control-Allow-Origin": "*",
                    "Content-Type": "application/json"
                },
                "body": json.dumps({
                    "error": "Missing 'job_description' or 'resume_text' in the request body."
                })
            }

        # ========================================================
        # 2) Prepare Bedrock Request
        # ========================================================
        bedrock = boto3.client(service_name='bedrock-runtime')
        model_id = os.environ.get("BEDROCK_MODEL_ID", "moonshotai.kimi-k2.5")
        
        system_prompt = (
            "You are an expert Applicant Tracking System (ATS) and a strict, "
            "professional Senior Technical Recruiter at a top-tier North American tech company. "
            "Your task is to objectively evaluate a candidate's Resume against a Job Description (JD) "
            "and provide a professional match analysis. Output ONLY valid JSON. Absolutely no other text. "
            "Do NOT include markdown formatting. Do NOT wrap the JSON in ```json blocks. Just output the raw JSON object. "
            "The JSON object MUST contain exactly the following keys: "
            "'ats_score' (integer), 'matching_keywords' (array), 'missing_keywords' (array), "
            "'actionable_feedback' (string)."
        )

        user_prompt = f"Job Description:\n{job_description}\n\nCandidate Resume:\n{resume_text}"

        # Using the standard bedrock converse API which simplifies multi-provider payload differences
        messages = [
            {
                "role": "user",
                "content": [{"text": user_prompt}]
            }
        ]
        
        response = bedrock.converse(
            modelId=model_id,
            messages=messages,
            system=[{"text": system_prompt}]
        )
        
        # ========================================================
        # 3) Parse Response and Return
        # ========================================================
        response_text = response['output']['message']['content'][0]['text']
        
        return {
            "statusCode": 200,
            "headers": {
                "Access-Control-Allow-Origin": "*",
                "Content-Type": "application/json"
            },
            # Return the exact JSON string generated by the LLM
            # (If it accidentally contains whitespace or newlines, API gateway handles it,
            # but we assume the model output is raw valid json as instructed).
            "body": response_text
        }
        
    except Exception as e:
        print(f"Error invoking bedrock: {str(e)}")
        return {
            "statusCode": 500,
            "headers": {
                "Access-Control-Allow-Origin": "*",
                "Content-Type": "application/json"
            },
            "body": json.dumps({
                "error": "Internal server error during ATS analysis.",
                "details": str(e)
            })
        }
